### ISSUE TITLE
Create a ship sheet

### ISSUE THREAD

**Issue by AlexOkafor** [winks-vtt/yze-coriolis#13]

**Comment by Necrot1c** [comment]
I have been working on this today, and have the basis of shipmodules / shipfeatures / shipweapons all created but got stuck at the JS for the sheet for the ship. Looking at the Free League sheet there are only a handful of editable fields with no logic with everything else just being items that can be dropped onto it.
Will keep digging to try and get at least a basic selectable and editable sheet over the coming days

**Comment by AlexOkafor** [comment]
@Necrot1c cool! Just a heads up I'm currently in the design phase for this sheet. Since ship sheets are almost just as pivotal to Coriolis as character sheets are, I wanted to do something that is just as fun to use.  I was wanting to do something a little more interactive than a basic ship sheet with form fields to help with the flow of the game. I just put this task here for those to follow along. But if the community can have an implementation that works in the interim that'd be great!

**Comment by Necrot1c** [comment]
Since the rolls are done against the characters skills, it would then be easiest to do it against the players Actor sheet (much like its done in Roll20 where its just a tab).
The only issue with this is that its then tied to only a single character or has to be duplicated to each player. Unless there is a way for the rolls to pull from the correct Actor when doing rolls. Crew positions could solve this as you have a pilot specified and when a pilot roll is done it pulls from the correct Actor. 
There will be instances where someone else will be filling a role because say the sensors operator is incapacitated. So maybe a popup asking which crew member is performing the task? This is all just me thinking aloud, I'm sure you have plans that actually work.

What I am trying to build however is a temporary placeholder ship sheet that (for now) players can just reference. The ship modules / weapons and features are all done the same as items / weapons etc for characters so have the field for bonus etc ready for anything automated to take place
