### ISSUE TITLE
Not all modifiers from Items are shown in rol dialog box

### ISSUE THREAD

**Issue by theczarek** [winks-vtt/yze-coriolis#263]
When rolling a skill only modifier from one item of any given type is shown e.g one Critical injury, one gear one talent of given type.
Modifiers from eg. multiple injuries shoud stack up: 
![obraz](https://github.com/winks-vtt/yze-coriolis/assets/83540404/ccf142a7-12ee-4752-87e3-5152ec9444cf)

**Comment by IrishWolf** [comment]
Hmm, I can't recreate that problem.

https://github.com/winks-vtt/yze-coriolis/assets/36819852/085d8bbe-a0b7-4854-b8ed-92e5d340aecd

**Comment by theczarek** [comment]
Drag and drop injury created in reprository. When you add them via "+ADD" button it's ok. But when dragging and droping it remembers only last one droped

**Comment by IrishWolf** [comment]
hmm, even there I can't reproduce its effect.

Can you press F12 (open console of Foundry) and look if there are any errors or warnings that may be related?

https://github.com/winks-vtt/yze-coriolis/assets/36819852/5ae6fdbc-735b-4026-88c9-6989cd2c7fe4

**Comment by IrishWolf** [comment]
Okay, with try and error i've got the gist of the problem.
If you take the same injury (or item/talent/whatever) multiple times from the same folder/compendium it will have the same ID behind it.
As the modifiers are grouped with the respective ID they won't be listed multiple times.

Will look into it, how to tackle that problem.
For the meanwhile you can either use the "+ Add" button or drag different items/injuries/talents into the sheet instead of multiple times the same and editing it afterwards.

**Comment by theczarek** [comment]
Thank You. 
I've checked, They can be from the same folder (root folder in my case) but cannot be duplicated via RMB option. 
![obraz](https://github.com/winks-vtt/yze-coriolis/assets/83540404/35be4007-cdaa-4f35-b0f3-47bb9ab30d6f)
aaa and bbb were created in via Creare Item option, bbb 2 is duplicate of bbb. All three shows diffrent ID's in top left corner (marked red):
aaa: VDzjZmLtvDJ8aAVB
bbb: yWc8xtUvJfmksKrl
bbb 2: 1lkg1GuwDCdY6YkF

Modifiers system can be really useful. (Also great rework of Starship sheet. Debt tracking and list of modules are great)

**Comment by IrishWolf** [comment]
The problem should be fixxed with #267
