### ISSUE TITLE
Equipping gear has no effect, encumbrance is always calculated

### ISSUE THREAD

**Issue by r-valyar** [winks-vtt/yze-coriolis#27]
Equipping gear has no effect, encumbrance is always calculated

![Screenshot 2020-09-14 211056](https://user-images.githubusercontent.com/63558984/93122251-d7a78f80-f6ce-11ea-86b8-34cc11d454b3.jpg)

**Comment by SesuUisu** [comment]
This is connected to issue #26 and could solved together.

**Comment by AlexOkafor** [comment]
@SesuUisu @r-valyar  Equipping was meant as a way to signify I have "X weapon equipped for this combat" even if you have another weapon in your inventory, since switching weapons takes an action.  Not having an item equipped doesn't mean you aren't carrying it. For now mostly as a way to jot down what you currently have in your hand. Maybe in the future it'll help with automation of rolls.
