### ISSUE TITLE
Weapons macro edit: add animations

### ISSUE THREAD

**Issue by raffaeledeantoni** [winks-vtt/yze-coriolis#49]
Hi how can I edit the standard macro of an Item [Weapon] in order to add an animation? 
I've already figured out how to do that in the macro bar, but I want to edit the Item macro, so that it's triggered automatically for everyone using that Item.

**Comment by AlexOkafor** [comment]
I'm not exactly sure I follow the nature of the question. Which animation are we referring to?

**Comment by SKYCH1EF** [comment]
> I'm not exactly sure I follow the nature of the question. Which animation are we referring to?

I believe the OP is trying to implement FoundryVTT modules like “Automated Animations” and “Maestro” into the Coriolis Foundry experience (as am I) but it seems those modules only work for D&D, Pathfinder, and Starfinder like games. 

Maybe its because in Coriolis users only roll the weapon die (melee combat skill / ranged weapon skill) and thats it. Maybe those modules are looking for a second damage macro? Idk im not a coder. But it would be AMAZING to be able to utilize automatic weapon animations and sound fx when players roll the dice.
